<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TwinCatGateway.Desktop\TwinCatGateway.Desktop.csproj" />
    <ProjectReference Include="..\..\src\TwinCatGateway.Ipc\TwinCatGateway.Ipc.csproj" />
    <ProjectReference Include="..\..\src\TwinCatGateway.Xae\TwinCatGateway.Xae.csproj" />
  </ItemGroup>
</Project>
