<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{b72daeb9-f97b-498a-8662-597d8e37f5bc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    gatewaySmokeTests : FB_GatewaySmokeTests;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
